### ISSUE TITLE
UI小建议

### ISSUE THREAD

**Issue by sdffdsa** [nkumstc/print#3]
File/add中的选择文件可以调一调，太难看了，同时可以限制一下mime类型：
accept="application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/pdf, application/vnd.ms-powerpoint, application/vnd.openxmlformats-officedocument.presentationml.presentation"

**Comment by New-Future** [comment]
嗯,这个确实不太美观，

**Comment by New-Future** [comment]
现在的界面可以了

**Comment by boooosh** [comment]
……原来我在用马甲发issue……
话说注册了之后改了密码但是忘了怎么破？

**Comment by New-Future** [comment]
首页下面有一个不起眼的[找回密码链接](http://yunyin.org/User/forget)
可以用手机，邮箱或者再次认证找回
@boooosh
